import logging
import subprocess
import sys
from pathlib import Path

from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

# Path to the py/ directory (sibling of odoo_reports/)
_PY_DIR = Path(__file__).resolve().parent.parent.parent / 'py'


class IccReport(models.Model):
    _name = 'icc.report'
    _description = 'ICC Amex Report'
    _order = 'write_date desc'

    name = fields.Char(string='Report Name', required=True, readonly=True)
    report_key = fields.Selection(selection=[
        ('daily_campaign', 'Daily Campaign Results v3'),
        ('calls_consolidate', 'Calls Consolidate Report'),
        ('call_disposition', 'Call Disposition Report'),
        ('visit_log_optblue', 'Visit Log Optblue Report'),
        ('visits_disposition', 'Visits Disposition Report'),
        ('pr_calls_duration', 'PR Calls Duration Report'),
        ('pr_escalation', 'PR Escalation Report'),
        ('service_level', 'Service Level Report'),
        ('optouts_dnc', 'OPTOUTS-DNC Report'),
    ], string='Report Type', required=True, readonly=True)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('generated', 'Generated'),
        ('error', 'Error'),
    ], string='Status', default='draft', readonly=True)
    file_data = fields.Binary(string='Generated File', attachment=True)
    file_name = fields.Char(string='File Name', readonly=True)
    file_size = fields.Integer(string='File Size (bytes)', readonly=True)
    generation_log = fields.Text(string='Generation Log', readonly=True)
    generation_date = fields.Datetime(string='Generated At', readonly=True)
    user_id = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user, readonly=True)

    # Mapping: report_key -> Python script filename
    _SCRIPT_MAP = {
        'daily_campaign': 'generate_daily_campaign_results_v3.py',
        'calls_consolidate': 'generate_calls_consolidate_report.py',
        'call_disposition': 'generate_call_disposition_report.py',
        'visit_log_optblue': 'generate_visit_log_optblue_report.py',
        'visits_disposition': 'generate_visits_disposition_report.py',
        'pr_calls_duration': 'generate_pr_calls_duration_report.py',
        'pr_escalation': 'generate_pr_calls_visits_escalation.py',
        'service_level': 'generate_excel_report.py',
        'optouts_dnc': 'generate_optouts_dnc.py',
    }

    # Mapping: report_key -> output filename (in py/reports/)
    _OUTPUT_MAP = {
        'daily_campaign': 'Daily_Campaign_Results_2026.xlsx',
        'calls_consolidate': 'Calls_Consolidate_Report_2026.xlsx',
        'call_disposition': 'Call_Disposition_Report_2026.xlsx',
        'visit_log_optblue': 'Visit_Log_Report_Optblue_2026.xlsx',
        'visits_disposition': 'Visits_Disposition_Report_2026.xlsx',
        'pr_calls_duration': 'PR_Calls_Duration_Report_2026.xlsx',
        'pr_escalation': 'PR_Calls_and_Visits_Escalation_2026.xlsx',
        'service_level': 'Service_Level_Report_2026.xlsx',
        'optouts_dnc': 'OPTBLUE_INSIGHT_OPTOUTS.txt',
    }

    def action_generate(self):
        """Generate the report by calling the Python script."""
        self.ensure_one()
        if self.report_key not in self._SCRIPT_MAP:
            raise UserError(_('No script configured for report: %s') % self.report_key)

        script_name = self._SCRIPT_MAP[self.report_key]
        script_path = _PY_DIR / script_name

        if not script_path.exists():
            raise UserError(_('Script not found: %s') % script_path)

        python_bin = sys.executable or 'python3'
        cmd = [python_bin, str(script_path)]

        _logger.info('Generating report %s: %s', self.report_key, ' '.join(cmd))

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300,
                cwd=str(_PY_DIR),
            )
            log_output = (result.stdout or '') + (result.stderr or '')
            if result.returncode != 0:
                self.write({
                    'state': 'error',
                    'generation_log': log_output,
                    'generation_date': fields.Datetime.now(),
                })
                raise UserError(_('Report generation failed:\n%s') % log_output[-2000:])

            # Read the generated file
            output_name = self._OUTPUT_MAP.get(self.report_key)
            if not output_name:
                raise UserError(_('No output file configured for: %s') % self.report_key)

            output_path = _PY_DIR / 'reports' / output_name
            if not output_path.exists():
                self.write({
                    'state': 'error',
                    'generation_log': 'Output file not found: %s\n\n%s' % (output_path, log_output),
                    'generation_date': fields.Datetime.now(),
                })
                raise UserError(_('Generated file not found: %s') % output_path)

            with open(output_path, 'rb') as f:
                file_data = f.read()

            self.write({
                'state': 'generated',
                'file_data': file_data,
                'file_name': output_name,
                'file_size': len(file_data),
                'generation_log': log_output,
                'generation_date': fields.Datetime.now(),
            })
            _logger.info('Report %s generated successfully (%d bytes)', self.report_key, len(file_data))

        except subprocess.TimeoutExpired:
            raise UserError(_('Report generation timed out after 5 minutes.'))
        except UserError:
            raise
        except Exception as e:
            _logger.exception('Report generation error')
            self.write({
                'state': 'error',
                'generation_log': str(e),
                'generation_date': fields.Datetime.now(),
            })
            raise UserError(_('Unexpected error during generation: %s') % str(e))

    def action_download(self):
        """Trigger download of the generated file via controller."""
        self.ensure_one()
        if self.state != 'generated' or not self.file_data:
            raise UserError(_('No file available. Generate the report first.'))
        return {
            'type': 'ir.actions.act_url',
            'url': '/icc/report/download/%d' % self.id,
            'target': 'self',
        }

    @api.model
    def _create_initial_records(self):
        """Create one record per report type (run once on install)."""
        existing = self.search([]).mapped('report_key')
        for key, label in self._fields['report_key'].selection:
            if key and key not in existing:
                self.create({
                    'name': dict(self._fields['report_key'].selection).get(key, key),
                    'report_key': key,
                })
